apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - service-metrics.yaml

configMapGenerator:
  - name: dnsdist-config
    files:
      - configs/entrypoint.sh
      - configs/dnsdist.conf
    options:
      disableNameSuffixHash: true
